name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  go_router: ^6.0.9
  http: 1.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
